### PR TITLE
New Knuckles SpecialFall Animation [REUPLOADED]

### PR DESCRIPTION
**Pull request by ishmael205**
Reuploaded due the the fact that it was added to the wrong directory.
Hopefully that problem will not occur this time.

### CODE REVIEW

**Comment by PowerpointSmasher** [comment]
Why hasn't this been pulled yet?

**Comment by LnktheWolf** [comment]
hey @bb010g you wanna see what this is saying about conflicts?

Otherwise, as long as you're sure this time, approved.

**Comment by RikiDVX** [comment]
I approve.

**Comment by ghost** [comment]
I approve as well.

**Comment by bb010g** [comment]
Sorry about the delay, I'll merge this today. It's being a bit funny about conflicts.

**Comment by bb010g** [comment]
For future reference, [this SO answer](http://stackoverflow.com/a/2089754/1098906) explains how to switch which binary you're using while resolving a merge conflict.

**Pull request merged**
