### PR TITLE
Misc. Snake improvements

### PR DESCRIPTION
**Pull request by jojmaht**
By @Rage17

### CODE REVIEW

**Comment by ghost** [comment]
For the uninformed, this adds Snake's box movements into the completion build.

**Comment by ewmb7701** [comment]
How exactly did you accomplish this? Did you just copy and paste the files, or did you open them with PSA? I'd like to avoid changing anything else about Snake's moveset or animations.

**Comment by ghost** [comment]
This was a copy paste from the Halloween build. I believe that in the issue thread for this you mentioned that you would look at the two moveset files and merge the box movements into 3.6 Snake.

**Comment by ewmb7701** [comment]
Okay that's what I was wondering. We can't be sure the PMDT didn't modify anything else from Snake when they did this. I think it'll be okay if we use the FitMotion file, but I'll open up PSA and take a look.

**Comment by ghost** [comment]
Yeah, the FitMotion file should be 1:1 aside from the box movements.

**Comment by ewmb7701** [comment]
Found a very interesting tool. Apparently Dantarion made a .pac moveset dumper that lets you see all of a moveset in text form. Found it here: http://opensa.dantarion.com/wiki/Main_Page

It's called DumpGui. This could be very vital to our project.

**Comment by ewmb7701** [comment]
Leaked changelogs confirmed that the only changes to Snake was his taunt walking. Merging.

**Comment by ghost** [comment]
where are these leaked changelogs(i'm curious)?

**Comment by ewmb7701** [comment]
Let me upload a Dropbox, right now they're only on 4chan: http://boards.4chan.org/v/thread/319440761/project-m-news

Dropbox: https://dl.dropboxusercontent.com/u/143448524/3.61%20Changelist.zip

**Comment by ghost** [comment]
Thanks a bunch.

**Pull request merged**
