### PR TITLE
Changed the codeset to load PED Samus

### PR DESCRIPTION
**Pull request by Karrotkonvoy**
A response to #3. I made the required changes in each codeset to max out Samus' costumes to 10 and load PED Samus.

Current implementation is very functional, but rough around the edges. Works fine in game.

However there are a few issues:
*Wrong icon on SSS

*Black Sheik icons on opponent's results

*Samus' gets caught in a ball of light if you try to transform with her final smash due to lack of a tenth zero suit.

### CODE REVIEW

**Comment by chaosblade77** [comment]
You can fix the transformation without opening up the 10th slot. I put the files for the default Zero Suit there and added all the appropriate icons and images and she transformed fine, without the duplicate Zero Suit appearing on the character select screen. If adding a 10th ZSS costume is outside the scope of the project that could be a workaround.

Also, that Sheik icon would be fixed in stgresult if you want to add that fix. Not sure which icon location the other one uses.

**Comment by somealternateaccount** [comment]
I dislike approving this if adding this means there's issues. I'd much rather get it right the first time. Is it possible for you to go back and resolve the Sheik stock icon change? Additionally, not having a costume for ZSS or duplicating her default into the 10th slot feels bad.

Also, I believe you're using an old build as that SSS has been reverted AFAIK.

**Comment by chaosblade77** [comment]
The icons should be an easy fix.

I don't think using a duplicate Zero Suit here is really a problem though, since the only purpose it serves is to keep the final smash from breaking if the player does opt to transform. The transformation simply isn't to a unique alt. It's completely transparent otherwise, since it doesn't show up on the CSS or anything. I'm not aware of any other solutions to fix the transformation issue unless a proper 10th costume was to be added, but I'm under the impression that isn't an option. And neither is simply leaving in a partially broken final smash.

But that's just my two cents. I don't think it's worth throwing a cool alt that was already in the build away for something so minor.

**Comment by Karrotkonvoy** [comment]
Ah, my bad about the SSS. I don't always swap assets in the virtual SD when testing codes. I see why it wasn't used then. I committed changes to replace the stock icons and added copies of the Zerosuit files so it doesn't crash upon final smash transformation. It only needs copies of the ZSS portraits and stocks to be presentable.

That being said, I'm a bit torn about putting it in as well. My main sticking point being the lack of a 10th zerosuit. Either way, I'll just document all the fixes for a personal build or anyone interested in it.

**Comment by Tottle** [comment]
Can you provide a link to this please? PED Samus not getting included because of a minor thing like a ZSS missing, when there is an updated pink ZSS in an identical style to every current ZSS on Brawl Vault, seems like a really dumb reason not to include it.

**Comment by Karrotkonvoy** [comment]
Alright, I got the last of the portraits and stocks up for the spare ZSS to load. There shouldn't be any other issues. So now it comes down to a question of should we implement it as is and move on, add an extra ZSS to even things out, or drop it entirely. As Tottle said, there are a couple unused colors from SJS' Zerosuit model pack, which the updated ZSS is very clearly based off of: http://forums.kc-mm.com/Gallery/BrawlView.php?Number=204298 

In terms of scope of the project, I would say that technically adding another ZSS color could be considered part of completing the PED suit. It just seems like a quick patch job to throw in a duplicate ZSS. I wouldn't be entirely opposed to adding in either pink or yellow, but only if one was updated to the new materials and specular map.

**Comment by bb010g** [comment]
:+1: for adding in a corresponding ZSS.

**Comment by Karrotkonvoy** [comment]
I was able to convert Pink and Yellow over. The textures were nearly identical to the way the older SJS files were arranged. I just used the new .pac as a base. All I had to do was some edits to the back.




Only room for one though...

**Comment by jgd124** [comment]
Yellow is my vote it fits the color of the actual suit. That said, Pink is closer to a previous Brawl color, so...

**Comment by ewmb7701** [comment]
I think that yellow will look much nicer with the PED Suit Samus; the color scheme is closer. 

Is this still missing stock icons in the STGRESULT and the SSS? If the correct stock icons were placed would they show up?

**Comment by Karrotkonvoy** [comment]
All the PED Stock icons were replaced. Asset-wise, everything is changed. Everything shows up just fine sans the icon on the SSS, but I believe that was a code issue persistent with every extended character right? Shouldn't be a problem either way if we keep the iconless SSS. 

I agree with the yellow ZSS. I'll just go ahead and commit that one since I'm not hearing strong opposition to a 10th ZSS.

**Comment by ghost** [comment]
Just to leave my two cents on a fiiting ZSS here, I suggest updating Brawl ZSS, as every other alt for Samus(except Dark Suit) has a ZSS model pairing that uses a different model than the default ZSS, and Brawl's design is how ZSS looks in Prime 3(where PED Suit comes from). I'm currently working on an edit that should hopefully bring Brawl ZSS more into line with the Other M based revamp.

**Comment by ewmb7701** [comment]
@Karrotkonvoy Okay, that's good to know. If it's just an issue on the SSS then as long as we don't add stocks to it then we'll be fine.

@Rage17 I like that idea. It makes the most sense canonically.

**Comment by Karrotkonvoy** [comment]
@Rage17 That's cool. I can just change the codeset(s) to load ZSS' tenth slot and pass it on to you. It currently loads a duplicate of the first ZSS.

**Comment by ghost** [comment]
@Karrotkonvoy That sounds good, thanks for this by the way.

**Comment by Karrotkonvoy** [comment]
@Rage17 no problem

Alright, everything should be good to go on my end.
Final change list:
+Codesets modified to load 10 Samus and 10 ZSS on the CSS
+ZSS placeholder for FitSZerosuit09.pac&.pcs
+Samus and ZSS portraits and stock icons changed in all locations.

**Comment by ghost** [comment]
image
image
image
image

Brawl ZSS edit. Made with Program's edit for Brawl ZSS to have glowing lights and a spec map as a base, added holster, hair, and eye textures from SJS ZSS version 1.

**Comment by ghost** [comment]
https://www.cubbyusercontent.com/pli/Prime%20ZSS.rar/_31fd4a0a5116421089845996c6d3fef0 There's a link to the Brawl ZSS revamp.

**Comment by ewmb7701** [comment]
Approved. We can add the ZSS in after, I would just like this to get merged before any other changes are made.

**Comment by bb010g** [comment]
Why should we add this in before the accompanying ZSS? Just merge them together.

**Comment by xshot** [comment]
I'm a little puzzled here, please correct me if I'm wrong, but are the @Rage17 alts he made, going to replace the existing ones? If so I would rather it not, as I feel the ZSS pmdt made was great and resembles what they wanted in their final product.

**Comment by chaosblade77** [comment]
That ZSS is for the 10th slot, so Samus can transform if you use her final smash with the PED suit. Without a costume in the 10th slot she gets stuck in the transformation animation.

**Comment by xshot** [comment]
@chaosblade77 Thanks for the clearup. So I am assuming it is only for the PED samus?

**Comment by chaosblade77** [comment]
Yes, it's an additional alt costume and wouldn't replace any of the existing ones.

**Comment by Karrotkonvoy** [comment]
I went ahead and added the ZSS and #238 fix that @Rage17 did since this was still open. I used the original Brawl CSPs and stocks for the ZSS since the area where the belt would be is not visible.

**Comment by Pr0gram** [comment]
I'm making a version that uses the New PMDT ZSS, but has the same look as prime 3 ZSS. I think it would fit in with the main build better. WIP http://i.imgur.com/ZMBUtae.png

**Comment by Kippy232** [comment]
Could someone create a comparison image between the ZSS alts created by @Rage17 and @Pr0gram ? I really can't see a difference between the two.

**Comment by ghost** [comment]
@Kippy232 
image

**Comment by Kippy232** [comment]
@Rage17 Ah, now I see. I feel like yours is more fitting to the style of the other alts, but that's not to say that the other is better or worse.

**Comment by Pr0gram** [comment]
It's not like it matters, either way my model is getting used in some way, I just felt that if the PMDT went to all the trouble to make a completely remastered model they wouldn't just throw in vBrawl ZSS at the end.
Edit: It just seems like they put a lot of work in to getting the new model made, and even adapted it for the alts not to use it.

**Comment by Karrotkonvoy** [comment]
I'm not sure how I feel about these. They're so similar sans a few facial features, and minor differences in patches of blue. @Pr0gram's edit does make it fit in with the others better overall, but it's so close to the first costume that it feels a bit redundant to me. I'm feeling more partial to a different color or costume concept at this point unless there's something we could add to differentiate it more.

**Comment by LoanSPW** [comment]
I like the idea of an upgraded Brawl ZSS as the 10th slot, but I'd prefer the yellow costume i've seen above...
-It fits better with the PED suit color
-The upgraded brawl costume looks way too similar to the regular blue one...

**Comment by Kippy232** [comment]
Hmm.. Samus is usually orange-ish and her zero suit is blue. Her PED suit is orange-ish but also more silver blue in the color scheme. What if you just do something similar to her zero suit? Maybe accentuate her usual blue with a metallic silver/off-white color? Just spit balling to differentiate from the base ZSS skin

**Comment by Tottle** [comment]
I think Program's face is looking much closer to the source material and more work put into it. Once finished it will look even better, so I am excited to see where it ends up.

**Comment by ghost** [comment]
@Tottle Yeah, Program's face probably does. On mine, I just reused the default costume's face textures aside from the eyes, for the sake of making sure that it looks fitting next to the existing costumes.

**Comment by Kippy232** [comment]
With the recent discovery of an albeit fake leak, a Corrupted ZSS was also leaked with it. It's still fake, but I feel like that would be a far better alternative skin than making her a different blue. _stares shamefully at Nintendo_ Issue https://github.com/TheOriginalSINe/Project-M-CC/issues/262 features a picture of Corrupted ZSS like five posts down. It's even supported canonically as stated here: http://metroid.wikia.com/wiki/PED_Suit

"At first, the corruption manifests as dark blue veins on the right side of her face, along the side her nose and around her eye. As the corruption progresses, the pupil of her right eye becomes opaque, electric blue in color (the other is unaffected). The color of her irises are accentuated, and the sclera of both her eyes (the white part of the eyes) become black. Her skin also takes on a blue hue."

**Comment by LoanSPW** [comment]
The corrupted ZSS wasn't in the leak however, so it's definitely fanmade.

It would go well with a Corrupted PED Suit however, but we have only one slot left.

**Comment by Karrotkonvoy** [comment]
Does the corrupted skin use Brawl Samus as a base? I'd say rebuild it using SJS' Samus. The other "leaked" orange suit also looks like a good option.

**Comment by Kippy232** [comment]
@LoanSPW Ah, I misunderstood. Still, maybe a Corrupted ZSS would be preferable to the current WIP alts. It's up to @Rage17 and @Pr0gram though, I suppose.

**Comment by Tottle** [comment]
Might as well post this here too: 

If Corrupted ZSS was less of a cliche evil costume, then I think it could be cool. The ghostly pale skin and garish blue face paint being too much to resemble the PMDT's level of professionalism. It looks like a cheap mod with all that. I would suggest using @Pr0gram's head in its place with perhaps very light touches of corruption from the beginning of the game outside the Zero Suit itself.

It should also be noted: she is only around 10% corrupted in the Prime 3 PED suit this costume is based off. So she should have at worst a very light blue vein on the right side of her face, not all that.

Look how you can't even see any facial corruption in the first pic, right after she gets the PED suit. http://metroid.wikia.com/wiki/Phazon?file=CorruptedFace.jpg

**Comment by Pr0gram** [comment]
I don't know if adding the PED suit is still under consideration, but if it is I'd like to presents my new ZSS to fill the missing 10th slot. It doesn't match the suit at the end of Prime 3, because many people thought that Prime 3 ZSS was to similar to default. It, however, keeps with the theme that 2/3 of ZSS's alts are based on ending outfits. This one is based on Zero Mission.
screencapture97

**Comment by Kippy232** [comment]
@Pr0gram It seems as though the idea of a Corrupt ZSS alt is far less popular than, for instance, a recolor. For that matter, I suggest a simple Strawpoll to determine which should be pursued, but I'm far more concerned with playing Samus in what I consider to be her best suit. While I still vote for a Corrupt ZSS alt, I think yours will do finely.

**Comment by Pr0gram** [comment]
@Kippy232 I asked Nano in chat the other day about Corrupt ZSS, because she was the obvious choice. He said that he didn't think Corrupt ZSS wouldn have been considered, because she is too much of a fan character.

**Comment by Kippy232** [comment]
@Pr0gram I understand, and that does make sense. At the end of the day, if I get to use PED suit Samus, I'm happy.

**Comment by Pr0gram** [comment]
@Kippy232 Me too!

**Comment by Karrotkonvoy** [comment]
@Pr0gram Love it. That would definitely be my choice out of all the ideas proposed. I assume the idea is still being considered since the pull hasn't been shut down. I was just waiting till we figured out what we were doing to modify and rebase the pull. The changes aren't particularly hard to implement into the master, just kinda tedious with the code and csps being located in multiple files that are being edited often.

**Comment by bb010g** [comment]
Closing due to reasons listed in #3.

**Comment by Kippy232** [comment]
So, just for clarification, is this alt benched indefinitely, or simply until February? Assuming, of course, that Nanobuds gives this an "okay."

**Comment by ghost** [comment]
@Kippy232  The Samus alt is benched indefinitely unless Nano changes their mind. @Pr0gram 's ZSS alt is fine, but would need a different Samus suit.

**Comment by bb010g** [comment]
Nanobuds gave explicit disapproval for use of this alt. As we'd need to come up with a new alt to replace it, it's benched.

**Comment by Kippy232** [comment]
Is the alt's very concept benched as well? What if someone presents a working model and everything, just not made by Nanobuds? Sorry I'm so persistent, this just really is my favorite one :/

**Comment by bb010g** [comment]
If someone makes their own PED suit model, that's fine and could very well get in. However, they'd need to wait until February to discuss its inclusion seriously.

**Comment by Kippy232** [comment]
Well alrighty then. Hopefully someone can make one by then. And, hey, maybe I'll learn how to do it by then! :smile:

**Pull request closed without merging**
