### PR TITLE
Allow Stage Builder stages

### PR DESCRIPTION
**Pull request by libertyernie**
Since Project M uses the /projectm folder, you can safely edit and use Stage Builder stages as long as you put them on the SD card, even if you're using the hackless version. These stages get stored in /projectm/st.

These changes remove the "Disable Custom Stages" code from the .txt files (I didn't include any updates to the GCT files - I figured you would be rebuilding them eventually), and edit the sc_selmap.pac file to put the "Page 1" icon in the correct place when showing the list of Stage Builder stages on the SSS (see that particular commit for notes on what I changed.)

By the way, maybe you should store those .txt files in UTF-8 or ASCII. Git doesn't recognize UTF-16 files as text, so you can't see the lines I removed here on GitHub.

### CODE REVIEW

**Comment by ewmb7701** [comment]
Approved. Glad to to see to see you contributing, you do great work!

**Comment by bb010g** [comment]
We should put a disclaimer somewhere that stages need to be stored to the SD card.

**Comment by darkralts** [comment]
So i can play custom stages on the latest build as long as there on the sd card?

**Comment by jojmaht** [comment]
Approved.

**Comment by bb010g** [comment]
@darkralts Yes, as you still need no stages on the Wii locally to run Smash Stack.

**Comment by darkralts** [comment]
How to u access the custom stages?

**Comment by bb010g** [comment]
...like Brawl? What did you even try?

**Comment by darkralts** [comment]
To play custom stages in project m cc.

**Comment by darkralts** [comment]
I use homebrew loader with disc not hackless

**Comment by bb010g** [comment]
> What did you even try?

Tell me what's not working as expected, and I can help you.

**Comment by darkralts** [comment]
Thwre is only page 1 and page 2 buttons on the stage screen and no custim
stages button

**Comment by JackpotSHUnited** [comment]
Did you make sure you built one?

**Comment by darkralts** [comment]
Yes and saved it to sd card. Shows up on projectm/ST

**Comment by libertyernie** [comment]
Is it possible you're using a build from before this change was added into it? The change was only applied to the trunk an hour ago.

**Comment by darkralts** [comment]
I downloaded the latest build, made a stage saved to sd card, and this is
the stage select screen

**Pull request merged**
