### PR TITLE
Improved CSS layout

### PR DESCRIPTION
**Pull request by bb010g**
From Nekudot. See #299.

On the topic of codeset changes, we should probably figure out a better way of making sure the text codeset is accurate and the WiFi is up to date.

### CODE REVIEW

**Comment by bb010g** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/TheOriginalSINe/Project-M-CC/pull-request/303/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=TheOriginalSINe/Project-M-CC)

**Comment by vdenzen** [comment]
This will crash with my latest PR, because i am also changing the codeset

**Comment by Nekudot** [comment]
I was thinking that too.

Just search and change this:
- 00090d0c 0515011a
- 0a071325 1002240e
- 0f140616 1f172903
- 04182208 23202e2b
- 2c2a0b19 112d212f
- 12262730 32310000

With this:
- 00090d0c 0515011a
- 120a0713 25030402
- 240e0f14 08232b2c
- 2a2e2006 161f0b19
- 112d2f21 17221018
- 32312627 30290000

**Comment by vdenzen** [comment]
Ah that will be an easy editie indeed, but i also got the problem that i got a few other changes tot the gct that i want to commit like giving knuckles all his cosmetic slots and Isaac his own franchise logo but the pmcc admins wanted tot pr all the issues seperately but if my pr's wont get accepted it will take a while before those fixes will be added to the main build

**Comment by Nekudot** [comment]
Yeah, having multiple PRs with code edits can slow down progress a lot, because it takes a while to aprove changes. I guess aproving either this or your announcer calls first, then redoing the other one is the only option if they can't be merged, and you'll have to upload your other edits little by little.

**Comment by bb010g** [comment]
Sorry about approval times. Sometimes someone has a testing setup at hand or someone else has already tested and it can get through quickly, but not always.

**Comment by cimpyhigh** [comment]
@vdenzen Could you link that .gct? Would love to use that in my personal build.

**Comment by ghost** [comment]
#299 has been updated to reflect previous discussion on CSS layouts. I won't approve this as I feel there has not yet been enough discussion. Particularly, nekudot's design has a number of drastic changes from what has been standard placement for a long time that I don't agree with.

**Comment by bb010g** [comment]
Closing until #299 is decided upon, as this is still up in the air.

**Pull request closed without merging**
