### PR TITLE
Announcer for Knuckles and Lyn

### PR DESCRIPTION
**Pull request by jojmaht**
Made by @vdenzen.

### CODE REVIEW

**Comment by bb010g** [comment]
Could we have some previews?

**Comment by ewmb7701** [comment]
Did this overwrite the "Stage Clear" announcement? I'd prefer if we could prevent that.

**Comment by vdenzen** [comment]
I don't know how to change the offsets of the clone characters so unfortunately it does. The Lyn one was inserted in an empty bank so won't remove anything. Maybe someone could change the offset to prevent that from happening

**Comment by ewmb7701** [comment]
Alright we can keep it for now. Would the offset be in the module file or the codeset?

**Comment by JCOnyx** [comment]
From the current announcer, I think splicing together the "Li" from Toon Link and the "N" in Ness, with a tiny bit of editing, would probably give us the best results.  Messing around with .sawndz files is something I've never done, but I have a lot of experience with Audacity.

If someone could get me those 2 files in .wav format I could probably give it a pretty good shot.

**Comment by vdenzen** [comment]
Nice i hope it works, i will send you the files after i'm done with work

**Comment by JCOnyx** [comment]
Figured out how to get the files myself.  Here was my attempt with nothing but the 3.6 announcer:  https://www.dropbox.com/s/wzhwglyca8u06ni/Lyn.wav?dl=0

Ended up using Link and Ganondorf.

**Comment by PyotrLuzhin** [comment]
@TheOriginalSINe The offset's in the codeset, not the module

**Pull request merged**
