### PR TITLE
Added Announcer Call for Isaac and Sami

### PR DESCRIPTION
**Pull request by vdenzen**
https://www.youtube.com/watch?v=BD74Xwrs0qo

Fixing issue #8 and Announcer: Sami

### CODE REVIEW

**Comment by Kippy232** [comment]
Do any of the announcer calls override any clips that may be heard elsewhere? For example, "Knuckles" overrides "STAGE CLEAR," I think

**Comment by ghost** [comment]
@Kippy232 I believe that Isaac's clip replaces SUCCESS! while Sami's may replace an unused one.

**Comment by Kippy232** [comment]
@Rage17 Well, that's certainly better than not having their own character calls. If it's possible to insert new calls, I think this should be addressed at a later date, but until then, that should only bother someone who uses Classic mode frequently.

**Comment by bb010g** [comment]
Approved, and we should go test to see what sounds are in need of fixing due to announcer calls.

[Approved with PullApprove](https://pullapprove.com/TheOriginalSINe/Project-M-CC/pull-request/295/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=TheOriginalSINe/Project-M-CC)

**Comment by pharoahfawcett** [comment]
why not replace something like "tourney" or "rotation"?

**Comment by Nekudot** [comment]
Tourney isn't playable, so sure.
Are the updated Knuckles and Lyn announcer calls included in this file too? Or are they not done yet?

**Comment by Kippy232** [comment]
@Nekudot hopefully so. Knuckles' call doesn't quite fit the others; and Lyn's sounds like "Ling!"

**Comment by vdenzen** [comment]
@Nekudot yeah they are

**Comment by jojmaht** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/TheOriginalSINe/Project-M-CC/pull-request/295/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=TheOriginalSINe/Project-M-CC)

**Comment by bb010g** [comment]
Needs to be merged with master before we :shipit:.

**Comment by Kippy232** [comment]
It's time :shipit:

**Comment by cimpyhigh** [comment]
Is this going to be 
image?

**Comment by bb010g** [comment]
Sorry, I can't read.

**Pull request merged**
