### PR TITLE
Knuckles and Sami animations

### PR DESCRIPTION
**Pull request by ghost**
Added 3rd wait animation + 2 victory animations for Knux, Added Wait 1 animation and Back Air Animation + Landing Animation to Sami

### CODE REVIEW

**Comment by bb010g** [comment]
Could you show these animations somehow (gif, video, &c.)?

**Comment by ghost** [comment]
Here's an example of Sami's new Wait1: 
brawlboxanimation0

**Comment by DestinyHiro** [comment]
Please wait before adding in any animations over Sami. The animations could use some further work, it could use a Wait2 and Wait3 animations before being included, also an improved Wait1 (since as shown it by her right hand looks incomplete). As for Knux, I haven't seen the animations so I can't say anything on that manner but I've heard the victory animation was pretty decent.

**Comment by bb010g** [comment]
What may work better is splitting this up into separate commits for each character.

**Comment by bb010g** [comment]
Yeah, just open up a new PR for just the Knuckles changes, with gifs. The Sami animations need  more work.

**Pull request closed without merging**
