### PR TITLE
Update to newer Knuckles leak

### PR DESCRIPTION
**Pull request by bb010g**
STAGE CLEAR

We'll need to fix up a couple of the taunts, but otherwise he's like butter.

### CODE REVIEW

**Comment by ghost** [comment]
Approved

**Comment by bb010g** [comment]
Approved previously by @skinnyfoetusboy.

**Comment by JackpotSHUnited** [comment]
Where did the new leak come from?

**Comment by bb010g** [comment]
Can't disclose. Sorry. :(

**Comment by bb010g** [comment]
Here's a summary of changes, courtesy of @ArtfulHobbes & @Rage17:
- Down tilt is faster
- F-smash explosion gfx removed, fully charged hitbox is same size as no charge.
- Up-B aerial height increased.
- Down-B Damage added to charge state
- Nair reworked to sex kick
- Down-air hand hitbox decrease active frames
- Back throw knockback increase. (Maybe angle was changed as well?)
- Up-throw angle changed
- Get up attack changed to spinning kick
- Crouch lowered in height
- Up-taunt looks more active
- Entry animation changed
- Proper clapping at results screen
- Wait 2
- EscapeN(spotdodge)
- Ottoto and OttotoWait(Ledge Teeter)
- Glide intro animation
- PMDT Vector, Charmy and Espio gear alts
- PMDT Tribal Knux color, White recolor, and grey ccolor changed to Black

**Comment by KymaeraK1ng** [comment]
When is the next update?

**Pull request merged**
