### PR TITLE
Lyn, Awakening Roy, Wii/Virtual Boy ROB, and CSS/ SSS fixes

### PR DESCRIPTION
**Pull request by jojmaht**
Awakening Roy has his proper eye textures, Wii ROB has corrected expressions, Virtual Boy ROB has corrected eye texture resolution. Lyn has metals and expressions, as well as CSPs. SSS icons now properly show stock icons.

PS: This PR should be merged before subsequent ones as some minor bugs are being fixed as of now.

### CODE REVIEW

**Comment by jojmaht** [comment]
For future reference, BP were made by @vdenzen and the rest is courtesy of @Rage17

**Comment by jojmaht** [comment]
@Rage17 Do you know which issues this fixes? If so, could you maybe reference those or close them directly?

**Comment by ghost** [comment]
@skinnyfoetusboy i'll check if there are issue entries for these later on today and close them, yeah.

**Comment by MrGameCrazy** [comment]
Still getting black eyes texture for Awakening Roy.

**Pull request merged**
