### PR TITLE
Fixed Roy not having eye highlight issue by adding it back

### PR DESCRIPTION
**Pull request by Pr0gram**
Purpasquirt fixed Roy's Black eye issue. In doing so he had to remove his eye highlight texture. Thsi simply adds it back in

### CODE REVIEW

**Comment by Kosyne** [comment]
I believe this was covered by #221.
Using the latest build vs your commit, I see:


Looking at the texture files, though, it seems your iris texture is antialiased and overall less rough (other than one stray pixel to the bottom-right of the pupil). The one I used from @skinnyfoetusboy's commit wasn't. I think it looks a bit better and would be in favor of adding this commit for that texture.

**Comment by Pr0gram** [comment]
Sorry, I didn't know Skinny had already fixed the highlight problem. Last I heard was that Purpa fixed Roy having black eyes, by removing his eye highlight texture.

**Comment by Kosyne** [comment]
I fixed that one, actually. However, I think this should still go through as yours has a better iris texture than what is in already.

**Comment by bb010g** [comment]
Approved for the iris improvement.

**Comment by ewmb7701** [comment]
Approved.

**Pull request merged**
