### PR TITLE
Added changes by Karrotkonvoy from Issue #58 that seem to have been overlooked

### PR DESCRIPTION
**Pull request by andy-bond**
Added Karrotkonvoy's changes (from Issue #58) to projectm/pf/menu2/mu_menumain.pac

These changes include:
- Changed "Clear" to "Retro"
- Changed Clear mode text description to "Play with N64 styled character models!"
- Changed Clear Mario Image to N64 Mario Image

This change will make it more obvious where N64 Mode is located (as many people have asked on Discord)

(Also, I'm LordGennai on Discord & Reddit)
Karrotkonvoy deserves the credit, I just made the PR since I thought this needed to be added.

### CODE REVIEW

**Comment by somealternateaccount** [comment]
Will take a look at this after finals today.

**Comment by jojmaht** [comment]
Approved.

**Comment by Azer-X** [comment]
Approved

**Comment by ghost** [comment]
Approved

**Comment by UltraSyko** [comment]
I love it. Much appreciated

**Pull request merged**
