### PR TITLE
Corrected Lyn's Black Dress Alt CSP/RSP/BP/Stock

### PR DESCRIPTION
**Pull request by HealthyMinmo**
Slightly adjusted Lyn's skin tone for her black dress alt's
CSP/RSP/BP/stock icon to match her in-game appearance.

### CODE REVIEW

**Comment by HealthyMinmo** [comment]
Here's what she looks like in-game:

dolphin 2015-12-13 17-38-19-44

Here's a comparison of her old and new CSP:
menselchrfaceb 355
menselchrfaceb 355

**Comment by HealthyMinmo** [comment]
Old and new BP's:
infface 074
infface 074

**Comment by bb010g** [comment]
It looks like the BP still has the lighter skin tone. Otherwise LGTM.

EDIT: Oh, old screenshot. :shipit: then

**Comment by HealthyMinmo** [comment]
And stock icon:
infstc 355
infstc 355

**Comment by HealthyMinmo** [comment]
(Yep, that was before I made any changes)

**Pull request merged**
