### PR TITLE
Awakening Roy black eye fix.

### LINKED ISSUE #198: Roy new alternate costume missing eyes
As you can see, his eyes are completely black. Tested on Dolphin. Normal costumes are alright.

### PR DESCRIPTION
**Pull request by Kosyne**
Fixes #198

### CODE REVIEW

**Comment by bb010g** [comment]
Does this just revert the file?

**Comment by ghost** [comment]
@bb010g , it doesn't. It has the eyes from v1 Awakening Roy(which the commit with the black eyes was supposed to have), while reverting the file would give it Marth's eyes.

**Comment by ewmb7701** [comment]
Approved. Looks good to me.

**Comment by bb010g** [comment]
Approved. :shipit:

**Comment by UltraSyko** [comment]
Our Boy looks slick

**Pull request merged**
