### PR TITLE
Replacement list now matches info.pac song names.

### PR DESCRIPTION
**Pull request by bb010g**
#186 is inactive and inaccurate. Please make sure these match up with info.pac. I think I got them all, but it's nice to double check.

### CODE REVIEW

**Comment by cimpyhigh** [comment]
Maybe change the "Hope you enjoy Project M!" to "Hope you enjoy Project M CC!" Just a thought.

**Comment by Kippy232** [comment]
I just realized that both A10 (Gritzy Desert) and A13 (Delfino Plaza) are changed to Metal Cavern (by MG3) in the Songs Replaced file. I'm not sure if this is intentional or not, but I don't think it is.

**Comment by cimpyhigh** [comment]
Is there a reason this hasn't been :shipit:?

**Comment by bb010g** [comment]
Remaking on a proper branch.

**Pull request closed without merging**
