### PR TITLE
Retro

### PR DESCRIPTION
**Pull request by PhoxFyre**
This changes fitmariospyxx and mu_menumain(changes character symbol)
these were made by Damon, jorge, purpasquirt, and stupidmariofan 1

### CODE REVIEW

**Comment by ewmb7701** [comment]
Approved. Looks good to me.

**Comment by bb010g** [comment]
What exactly is the character symbol change? Also, [rebase](http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing).

**Comment by ghost** [comment]
@bb010g it seems to be a change for the Special Brawl menu to show the fixed SSB64 Mario, and not the PMDT one, which had a certain issue. (Someone accidentally overoptimized the PMDT one in the leak, as there are features in it that are actually a bit blockier than they should have been, with Mario's ears being reduced to basically a literal triangle in the PMDT one.)

**Comment by PhoxFyre** [comment]
how do i rebase?

**Comment by Karrotkonvoy** [comment]
The new models look good. However, I don't think Mario's pose in the menu files really matches the others as well as it could. I went ahead and tried redoing the pose since I had the animation file lying around.

Original:
menspecial13

New model, used in this pull:
menspecial15

Another one i made using the new model:
menspecial15 3

**Comment by PhoxFyre** [comment]
there's a newer update
so im closing this pr

**Pull request closed without merging**
