### PR TITLE
Lyn CSP update

### PR DESCRIPTION
**Pull request by vdenzen**
Small update where i added the right hair wrap on the CSP and BP. And
testing github pull.

### CODE REVIEW

**Comment by vdenzen** [comment]
Allright, this is the first time i am using github and i see that it wants to commit 2 things instead of one. I only want it to pull the Lyn CSP updates.. Don't know if this all goes well..

**Comment by bb010g** [comment]
Try a new PR, but this time fast-foward your master first and then branch and commit.

**Comment by ewmb7701** [comment]
So is this alright to merge? Is it up to  date?

**Comment by bb010g** [comment]
It's overly dirty to merge right now. I can try to cherry pick the commit though.

**Comment by bb010g** [comment]
~git magic~

Merged in 0200cc2. Sorry about the authorship not being kept. :(

**Comment by vdenzen** [comment]
Ah no problem, need to understand how github works. It is the first time i'm using a system like this so i knew errors will occur. But thanks that u pushed my new stuff anyways!

**Pull request closed without merging**
