### PR TITLE
New codeset for alternate stages

### PR DESCRIPTION
**Pull request by jojmaht**
Adds the codes from Issue #57

### CODE REVIEW

**Comment by UieSolverofThings** [comment]
Thank you! ^^

**Comment by ewmb7701** [comment]
Did you use Mewtwo's ASL tool for this? I'd like to add this to the text codeset if I can.

**Comment by UieSolverofThings** [comment]
At first I set up all the pointers myself in case ASL would conflict, but I've seen no problems when using the ASL tool to add them, so that's the version I uploaded.

**Comment by ewmb7701** [comment]
I'll need to add this specific ASL code to the text codeset, but I'll merge this now.

**Pull request merged**
