### PR TITLE
various costume fixes & improvments

### PR DESCRIPTION
**Pull request by vinegar97**
Updates shogun DDD and punch out DK's texture to a higher resulotion,
improves giga bowsers recolors, adds metal effect to mewtwo and roy's
kirby hats, adds shiny intro effect to vbrawl red hat pikachu, and
generally improves outset toon link's models

### CODE REVIEW

**Comment by ghost** [comment]
There were no issues for a number of these changes.

Please provide before and after screenshots for each

**Comment by vinegar97** [comment]
http://imgur.com/a/ZhbdR#9

http://imgur.com/a/e5ynX#5



al_151218_2235 1 bin out

al_151218_2235 bin out

al_151218_2249 bin outedit

(it's less noticeable with DK, but i assure you its there)

**Comment by ghost** [comment]
Looks good. Have you tested for lag? What's the difference in file size? Specifically for DDD and DK changes

**Comment by ghost** [comment]
@Azer-X those have been tested by people since sometime before 3.6 Beta (as they've been available in that thread for quite some time), and don't lag.

**Comment by Azer-X** [comment]
Which thread?

Anyways, Approved.

**Comment by ghost** [comment]
@Azer-X http://smashboards.com/threads/project-m-visual-fixing-updating-thread-lastest-update-10-03-15.384954/

**Comment by vinegar97** [comment]
@Rage17 thanks for having my back :+1: 
@Azer-X thanks for the approval

**Comment by ghost** [comment]
Approved

**Comment by ewmb7701** [comment]
Approved. However we need to update the ReadMe with credits.

**Comment by ghost** [comment]
@TheOriginalSINe For the sake of credits, I am Rage83 on Smashboards.(I made a fix or two in that thread)

**Comment by vinegar97** [comment]
alright here's a list: 
Codex9/MagicManNo9 for the PM visual fixing thread and shogun DDD,giga bowser and outset toon link fixes

rage83/rage17 for the boxer DK fix and making the shiny pikachu issue known

i did the roy & mewtwo metal hats and the implemented the shiny pikachu intro fix

tell me of i missed anyone

**Comment by vinegar97** [comment]
oh and Aghanim completed toon link's fixes

**Pull request merged**
