### PR TITLE
Removal of Nanobuds from readme, per his request

### PR DESCRIPTION
**Pull request by ghost**
Title

### CODE REVIEW

**Comment by bb010g** [comment]
We should figure out some better way of doing thanks. Approved for now.

**Comment by Kippy232** [comment]
Maybe a "Special Thanks" section for people like Nanobuds (understandably, he may want to be completely left out) and just a "Credits" section otherwise. I feel like deciding who fits where is up to the more active contributors. Just a suggestion

Edit: Or simply just a Special Thanks section, instead of credits. In this section, we could thank Nanobuds, as well as anyone who contributed indirectly, but not give a reason why. At the same time, we could actually credit people who helped, and whose assets were used.

**Comment by ghost** [comment]
@Kippy232 @bb010g Nanobuds explicitly wants to be left out of credits entirely.

**Comment by Kippy232** [comment]
@Rage17 Ah, okay. I retract my suggestion, then. Though I suppose, if anyone's a stickler about the differences between a "Credits" and "Special Thanks" section, my idea isn't so unneeded.

**Comment by somealternateaccount** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/TheOriginalSINe/Project-M-CC/pull-request/290/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=TheOriginalSINe/Project-M-CC)

**Comment by bb010g** [comment]
All this needs is to be updated to master (merge or rebase) and we're good.

**Comment by ghost** [comment]
@bb010g This was updated to master just now.

**Pull request merged**
