### PR TITLE
Created HowToContribute.md to Help People Understand Git - Modified README to link to new file.

### PR DESCRIPTION
**Pull request by andy-bond**
Created guide on How To Contribute to the Project covering topics such as Pull Requests, Merging, Squashing Commits, Helpful Links, etc. Also updated README to link to this new guide.

### CODE REVIEW

**Comment by ewmb7701** [comment]
Approved. However, having a guide for the desktop client might be good too. It's much easier than command line stuff, and it's what I use.

**Comment by andy-bond** [comment]
@TheOriginalSINe I agree there should be a section for that as well. Someone else will have to add that section to the guide later though after it's pulled into the build.

**Comment by hhsnopek** [comment]
To keep in suit of other git repositories the file should be name `CONTRIBUTING.md`. 

IMO I think references to usage of git and it's desktop component should reference outside sources. Like [git-scm.com](//git-scm.com), which is great for cmdline usage and understand git itself. This way you don't have to respecify the guide and wording later down the line. 

Here's a list of good references:
- [git-scm.com](//git-scm.com); git understanding and cmd-line usage
- [try.github.io](//try.github.io/levels/1/challenges/1); cmd-line tutorial
- [chris.beams.io/posts/git-commit](http://chris.beams.io/posts/git-commit); proper git messages

I'm am biased in thinking that the cmd-line is better once you've used it for a bit, for beginners I recommend the GUI then, once understanding Git, switching to the cmd-line as it's more powerful.

happy hacking! :grinning:

**Comment by andy-bond** [comment]
@hhsnopek I did link to git-scm.com, but I wasn't trying to make a comprehensive tutorial on Git. This is a quick guide to get people started. There are lots of Git Tutorials - nobody wanted to watch them. I explained the process to multiple people on Discord and figured this was easier than repeating myself! :)

**Comment by ghost** [comment]
Approved

**Pull request merged**
