### PR TITLE
Knuckles SFX fixes and alterations

### PR DESCRIPTION
**Pull request by Karrotkonvoy**
I fixed a some of Knuckles' more apparent sound issues. Many of his Sub Actions still use sounds from Sonic's soundbank. This is why some are either missing or playing Sonic's sounds mistakenly.
#161: I gave him his ledge balance (ottotto) voice clip and used it for neutral dodge and air dodge. I'm thinking the dodge roll sound is intentional and works fine.
#81: I changed his victory and taunt SFX entirely and reused sounds present in Knuckles' soundbank. I also removed the graphical effects since they didn't coincide with the animation.

It might be a good idea down the line to try and merge Knuckles' sounds with Sonic's like PMDT eventually did with Roy and Mewtwo since they share so many of the same sounds.

### CODE REVIEW

**Comment by Kippy232** [comment]
Yay! Knuckles is less awkward! :smile:

**Comment by ghost** [comment]
@Karrotkonvoy I've made my own fix for many of Knuckles' sound issues. Maybe we should look into combining them?

**Comment by Karrotkonvoy** [comment]
@Rage17 Might as well. You got a change log or something like that? I tried to log my changes for each sub action in the event of some kind of merge.

**Comment by ghost** [comment]
@Karrotkonvoy not really, but i basically just looked at Sonic and Knuckles sounds, and wherever Sonic reused sounds between his own animations, I did a comparison to make Knuckles point to his own equivalents of Sonic's sounds. Also, i got rid of the Sonic voices on taunts, and had changed down taunt to reuse side taunt's Knuckles clip.

**Comment by Karrotkonvoy** [comment]
@Rage17 Yeah that's pretty much what I did. I also added some jab and landing sounds that synced up with the taunt and victory animations. I didn't really venture beyond what I listed, but there are quite a few animations that use more subtle sounds not currently available in Knuckles' soundbank.

**Comment by ghost** [comment]
@Karrotkonvoy Oh, I realized something. My FitKnuckles  has the floaties from Sonic implemented(as both characters usually can't swim in their own games).

**Comment by Karrotkonvoy** [comment]
@Rage17 Didn't think of that one. I don't really think Knuckles needs those honestly. He was a pretty good swimmer in Sonic Advance and Sonic Adventure 2 at least.

**Comment by ghost** [comment]
@Karrotkonvoy It's there on Sonic because in _most_ games he can't swim, and i have it on Knuckles for the same reason.

**Comment by Darquezze** [comment]
Probably off topic but the animations for Knuckles' taunts (except the chuckle) have animations and sounds that don't fit in.

**Comment by Kippy232** [comment]
@Darquezze Could you be a bit more specific? I'm not exactly sure what you mean.

Is Issue https://github.com/TheOriginalSINe/Project-M-CC/issues/280 addressed in this fix?

**Comment by Karrotkonvoy** [comment]
@Rage17 I see where you're coming from, but Sonic being a terrible swimmer was always one of his character attributes. I think the reason for him being the only character with a life jacket in the Olympic games and water wings in PM is more of a call out to that rather than the gameplay itself. That combined with Knuckles' abilities in the games I mentioned make it seem unfitting for him to me.

@Kippy232 No, just what I mentioned so far.

**Comment by Darquezze** [comment]
@Kippy232 Like when Knuckles says "Bring it on", I don't think it matches the left/right taunt

**Comment by Kippy232** [comment]
Could someone check to see how well this pull works with pull https://github.com/TheOriginalSINe/Project-M-CC/pull/288? It may break this, so it's possible this needs to be touched up some.

**Comment by bb010g** [comment]
Yeah, this should just be redone in a new PR on the new Knuckles.

**Pull request closed without merging**
