### PR TITLE
New Knuckles SpecialFall Animation

### PR DESCRIPTION
**Pull request by ishmael205**
I've made a new animation for Knuckles' special fall, rather than it just being Sonic's special fall.

### CODE REVIEW

**Comment by bb010g** [comment]
Could you give a preview (gif, video, whatever)?

**Comment by ishmael205** [comment]
I can in an hour.

**Comment by LnktheWolf** [comment]
After you provide a preview, I can sign off on it if it's good quality.

**Comment by ishmael205** [comment]
@bb010g @LnktheWolf Here you go https://drive.google.com/file/d/0B1kkOrjXa4_ON1c2cnVlMUNVYjg/view?usp=sharing

**Comment by LnktheWolf** [comment]
@ishmael205 
is there any way to make it transition from the normal fall to special fall smoother?

**Comment by ishmael205** [comment]
@LnktheWolf There is. It's apart of the spring animation.

**Comment by LnktheWolf** [comment]
Ahh ok, my bad.
Approved. @thecoolguy27 or @bb010g wanna sign off and merge?

**Comment by bb010g** [comment]
Approved.

**Comment by ghost** [comment]
@ishmael205 atm the airdodge transition into special fall is missing.

**Comment by chickangamer** [comment]
Why you delete the link

**Comment by ishmael205** [comment]
@Rage17 It'll be added once make a new airdodge animation.

**Pull request merged**
