### PR TITLE
Lyn: Roll and Spot dodge normalization

### PR DESCRIPTION
**Pull request by ArtfulHobbes**
I changed Lyn's dodges to match the rest of the cast.

Spotdodge: Intangibility frames 2-21 FAF 31
Forward roll: Intangibility frames 4-19 FAF 32
Backward roll: Intangibility frames 4-19 FAF 32

### CODE REVIEW

**Comment by somealternateaccount** [comment]
Her spotdodge being on the Bowser/Dedede/Wario tier seems a bit weird, with FAF at 30. Lyn feels more like a character who would have a FAF 28 spotdodge e.g. Roy, Marth, Ike, etc. Is it possible to speed these up a bit? I'll look for the issue about this, there was discussion there I think.

**Comment by somealternateaccount** [comment]
Looking at #157, it seems like the roll changes are good, should this framedata be correct (will test).

Looking at #155, it seems like perhaps her spot dodge should be 25 frames after all? #155 definitely needs more discussion about what spot dodge tier she should be in.

**Comment by ArtfulHobbes** [comment]
It seems she should either be 25 tier (given she's a faster character)
or 28 tier (making her equal all other fire emblem characters)

In my opinion, I think we should match her up with the other Fire emblem characters. I'll wait on people opinions, then I'll update her spotdodge again.

**Comment by aFracture** [comment]
I vote for 25 tier. Her having the same spotdodge as Ike just seems unfitting haha.

**Comment by Grangach** [comment]
I would go for 25 tier too, I don't think consistency with the other fire emblem characters is too critical.

**Pull request closed without merging**
