### PR TITLE
Retro Mode

### PR DESCRIPTION
**Pull request by PhoxFyre**
Update

### CODE REVIEW

**Comment by bb010g** [comment]
Still needs a rebase. If you want a walk through, just come over into the Gitter or Discord.

**Comment by bb010g** [comment]
Ping?

**Comment by Kippy232** [comment]
Is this Pull still being worked on? I'd really like to see Retro Mode one step closer to completion.

**Comment by ghost** [comment]
@Kippy232 by now this Pull Request is heavily out of date. More updates are on the Discord chat.

**Comment by bb010g** [comment]
Yeah. This should just be redone when ready.

**Pull request closed without merging**
