### PR TITLE
Rearranged CSS to Dev Style - Fixes #299

### LINKED ISSUE #299: CSS Arrangement
really minor, but the "random" icon is in a rather random spot with the new arrangement

my suggestion would to swap "random"'s placement with game & watch, then move random to the far right. this would make the most sense if the original PMDT character order is being ignored (i.e swapping Wario and Mario)

### PR DESCRIPTION
**Pull request by andy-bond**
- Rearranged the CSS to the Dev Style as discussed in #299 
- Updated the files in both the wifi and normal codeset.
- Updated the codes in the text codesets in [Text Codesets]

Note: Wifi code is untested. Sami wasn't even included in the Wifi CSS before I made my modification.

Thanks to Nekudot for supplying the codes.

### CODE REVIEW

**Comment by ithunderHD** [comment]
I tested the WiFi codeset with Wii and it doesn't work

**Comment by ithunderHD** [comment]
It boots back to the wii menu

**Comment by andy-bond** [comment]
I don't think anyone has updated the Wifi codeset in a while, so Pyotr's codes to add Sami likely weren't added, etc.

**Comment by bb010g** [comment]
LGTM

**Pull request merged**
