### PR TITLE
Updated Title Screen

### PR DESCRIPTION
**Pull request by jojmaht**
Made by @vdenzen.
Screenshot : 
rkqu4l7

### CODE REVIEW

**Comment by ghost** [comment]
:shipit:

**Comment by bb010g** [comment]
Could you put up a new picture with the shape change?

**Comment by vdenzen** [comment]
http://i.imgur.com/w0lCnfn.png

I heard someone is cleaning up the edges and shadows so a little better version will be available soon

**Comment by vdenzen** [comment]
Updated with a better quality image
https://www.dropbox.com/s/ttjm96uf9zc351z/sc_title.pac?dl=0

**Pull request merged**
