### PR TITLE
Knuckles - New Victory Animation & 3rd Wait Animation by @thecoolguy27

### PR DESCRIPTION
**Pull request by andy-bond**
Added new victory animation for Knuckles, Added 3rd wait animation for Knuckles - Changes made by @thecoolguy27

### CODE REVIEW

**Comment by ghost** [comment]
brawlboxanimation0
brawlboxanimation5
Here's what they look like.

**Comment by KymaeraK1ng** [comment]
Woo!
When will the next update be?

**Comment by cimpyhigh** [comment]
The first win animation looks a little rough at the end. The fly-in is great, but the thumbs up still looks a bit jerky. Still better then what it is now though.

**Comment by PowerpointSmasher** [comment]
Yeah the thumbs up is awkward

**Comment by RikiDVX** [comment]
The wait looks alright, but I'm not so sure about the win animation.

**Comment by bb010g** [comment]
The foot sliding in the wait is odd. As for hands, could you make not make them clip? It's a wait and should be avoided if possible. Also, dread clipping. Could you brush the dread to the side a bit when a hand comes in?

It'd be neat if Knuckles could just go in to a ground punch after the loop like he does out of glide in game. The current stand up is too slidey and the actions are visibly divided (turn, arms up, arms to thumbs up position). People mix actions together a bit, flowing between them.

The base ideas aren't bad, but the execution isn't there yet.

[This may be useful for reference.](http://www.sonicworld.net/site/media/sprites/knuckles/)

**Comment by ghost** [comment]
It would looks awkward if I made both legs be put into the air at the same time at the beginning of the wait, so I left one foot sliding deliberately. And I suppose I could prevent dread clipping with his hands for the wait too.

**Comment by bb010g** [comment]
I like the arms in the new wait, but the feet are doing a weird jerk all alone. Could you make the tail turn with him a bit to better show the general torso twist? Also, turning the knees along a bit too wouldn't hurt.

Thumbs up motion in win looks better. The feet clip into the ground on impact and a weird bounce happens. IMHO the whole impact could use some more "oomph", but that's just me.

cc/ @bringobrongo @vinegar97 @Large-Leader

P.S. Before this gets merged, it should be rebased. It doesn't have to happen right now though.

**Comment by bringobrongo** [comment]
Approved.

**Comment by davidvkimball** [comment]
Approved.

**Comment by bb010g** [comment]
@andybond006 If you need help rebasing, http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html is good. You will have to `git push --force` though because you rewrote history, but it's fine here. No one was working off of this branch.

**Comment by andy-bond** [comment]
@bb010g should be good to go now. I actually had done all of the rebasing already, but accidentally merged and pushed instead of force pushed.. :(

**Comment by RikiDVX** [comment]
Approve +1

**Pull request merged**
