### PR TITLE
Retro Mode

### PR DESCRIPTION
**Pull request by PhoxFyre**
same as last but adding n64 luigi
courtesy of Damon, purpasquirt, and stupidmariofan1

### CODE REVIEW

**Comment by PhoxFyre** [comment]
sorry i have no clue how to rebase in github for desktop

**Comment by ewmb7701** [comment]
Approved. The commits look a bit messy, but it seems fine to me.

**Comment by North101** [comment]
Guide to rebasing based (pun not intended) on http://stackoverflow.com/a/7244456

Add the remote, call it "upstream":
`git remote add upstream git@github.com:TheOriginalSINe/Project-M-CC.git`

Fetch all the branches of that remote into remote-tracking branches, such as upstream/master:
`git fetch upstream`

Make sure that you're on your master branch:
`git checkout master`

Rewrite your master branch so that any commits of yours that aren't already in upstream/master are replayed on top of that other branch:
`git rebase -i upstream/master`

This should open a file with your default editor. Change all commits except the first to `squash` instead of `pick`. e.g.
Before:

```
pick commit3 message3
pick commit2 message2
pick commit1 message1
```

After:

```
pick commit3 message3
squash commit2 message2
squash commit1 message1
```

We have rewritten git history so we need to force push our changes. There is no going back after this:
`git push -f origin master`

**Comment by bb010g** [comment]
Once you rebase, approved.

**Comment by PhoxFyre** [comment]
like i said i cant rebase because i dont know how to do it in github for desktop
sorry

**Pull request closed without merging**
