### PR TITLE
Sami addition to the roster

### PR DESCRIPTION
**Pull request by PyotrLuzhin**
I’ve included a codeset and all of the relevant files to allow sami to
be accessed from the CSS. If there are any issues, let me know.

Known issues: Sami does not have any recolors for her stock icons, CSPs
and BPs. I believe that the individual on reddit who made them will
make more at some point (maybe).

### CODE REVIEW

**Comment by ghost** [comment]
Program on the Discord has made Sami recolors, he can send them your way sometime soon.

**Comment by somealternateaccount** [comment]
Noting here that this conflicts with the PED Suit changes due to codeset changes.

**Comment by bb010g** [comment]
Could you make sure to [rebase](http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing) into one commit before before merging?

**Comment by cimpyhigh** [comment]
This is great, excited to see Sami in her own spot on the roster. Unfortunately, I've been messing with the code all morning and have yet to see Sami. What am I supposed to do to add her?

**Comment by darkralts** [comment]
Could someone send a screenshot so i can see?

**Comment by bringobrongo** [comment]
Hey, for some reason this makes Snake crash on multiplayer and Sami instakills when she is thrown

**Comment by applesandgrapes** [comment]
hey, im the guy who made the stock icons. I can make more once someone makes/points me in the direction of recolors for her.

**Comment by cimpyhigh** [comment]
Is there a reason this hasn't been passed yet?

**Comment by bb010g** [comment]
Blocked on rebase and fixes for the issues @bringobrongo was describing.

**Comment by cimpyhigh** [comment]
This hasn't applied to mine yet... Snake works fine, throws work fine

**Comment by bb010g** [comment]
@cimpyhigh Are you using `TheOriginalSINe:master` or `PytorLuzhin:master`? These changes aren't on the main master yet; that's why they're in a PR.

**Comment by CervantesE** [comment]
Yeah, I can't get the build to load. For some reason, it keeps loading brawl instead. Based on the thread, it seems to be a problem that only I'm having, so any help would be appreciated.

**Comment by cimpyhigh** [comment]
@bb010g I am using your build with his codes and a couple other custom things, notely U.N. Owen's Isaac.

**Comment by Darquezze** [comment]
@crimpyhigh are thedudemonn's Voice for Isaac going to be included? It's so fits the character perfectly in my opinion

**Comment by ghost** [comment]
@Darquezze the soundbank and SFX will probably see some use, but the voice will probably be changed to something else, as it currently uses a random voice that "fits," and not one spcecifically for Isaac.

**Comment by CervantesE** [comment]
@Rage17 To be fair, Isaac is a silent protagonist.

**Comment by Darquezze** [comment]
@Rage17 I think one of the people working on Project M CC should voice Isaac. Ness and Lucas never had a voice but someone voiced them in the Smash games.

**Comment by cimpyhigh** [comment]
@Darquezze 
I don't think he was planning on adding his sound effects, but I went through and did it with my own build. I can link it if you would like.

**Comment by CervantesE** [comment]
@cimpyhigh Yes please!

**Comment by cimpyhigh** [comment]
Here is U.N. Owen's Isaac with thedudemonn's SFX. All credit goes to them. You have to add in the code by yourself. Also, I am not responsible for any PSA glitches. Haven't found any though.

https://www.mediafire.com/?gjvl45e8voy5l7r

**Comment by Darquezze** [comment]
@crimpyhigh good so far (are part of PM CC?)

**Comment by cimpyhigh** [comment]
@Darquezze I am not part of the PM CC. I can't do much brawl modding other than little texture hacks, small moveset edits, or making some really low quality csps. Also, btw it's cimpyhigh, without an r. Another thing, Isaac's Ragnarok sometimes glitches on certain stages with this moveset. It causes him to teleport. Again, I am not responsible.
EDIT: This has gone way off topic of the whole Sami thing... Is there anywhere on here that I could post custom content without it being a pull request? Like making a long-standing issue called "Custom Content" for people to post their mods?

**Comment by vdenzen** [comment]
@cimpyhigh You can go on the discord discussion channel https://discord.gg/0gfdMUkajXaUVpzF

**Comment by bb010g** [comment]
[**@cimpyhigh**](https://github.com/cimpyhigh) commented on [Dec 31, 2015, 4:04 AM PST](https://github.com/TheOriginalSINe/Project-M-CC/pull/230#issuecomment-168182814):

> @Darquezze I am not part of the PM CC.

What PM CC? There isn't really a CC group or team. People can just contribute here. You don't need to join anything.

**Comment by Darquezze** [comment]
Currently does Sami have any recolors or has been added to a current build?

**Comment by cimpyhigh** [comment]
As far as PM CC goes, I just meant I wasn't a mod here. The only downside of posting on the discord is that not everyone checks there (including myself)

**Comment by bb010g** [comment]
Approved.

Instadeath can be fixed once Sami's more usable and the Snake issue is with custom content on top (so really just separate thing). :shipit:

**Comment by cimpyhigh** [comment]
I still don't have any insta-death issues but that's just me...

**Comment by Darquezze** [comment]
Has sami been able to get on the roster? Without taking Snake out? Even is she's broken she should still be added to the roster

**Comment by bb010g** [comment]
@Darquezze This pull request puts Sami on the roster, as noted in the title. Sami is not removed.

**Comment by Darquezze** [comment]
What I ment is does she have her own slot yet on the roster? (Unless that's what u mean on the title.)

**Comment by Darquezze** [comment]
And does she have any recolors currently?

**Comment by Darquezze** [comment]
Forget about does she have any recolors part since I forgot to read the title

**Comment by bb010g** [comment]
This is not the place to ask about recolors. The Discord, Gitter, or another issue would be better. This is for just making her selectable.

**Comment by Darquezze** [comment]
@bb010g yeah, I know that's why I said to forget that part. But I what I truly want to know when there gonna give her own slot in the upcoming builds.

**Comment by cimpyhigh** [comment]
Oh, there's a code you need to remove, I think. I must have forgotten to do this in the PMCC stuff I uploaded. 

C2771688 00000011
D8220018 807F0010
80630060 38820020
38A00000 3D408077
614A866C 7D4903A6
4E800421 C8220018
C05F0020 815F0010
812A0008 81290110
2C090000 41800044
2C09002F 4181003C
3D00901B 61087E00
1D290008 7C084C6E
EC000072 80EA0018
C0470040 EC0000B2
C042002C EC02002A
D0010014 C042003C
D041000C C0480004
60000000 00000000

This is what Pyotr said you need to do to fix the insta kill when thrown

**Comment by PhoxFyre** [comment]
nice

**Comment by bb010g** [comment]
[**@cimpyhigh**](https://github.com/cimpyhigh) commented on [Jan 5, 2016, 10:19 AM PST](https://github.com/TheOriginalSINe/Project-M-CC/pull/230#issuecomment-169087286):

> Oh, there's a code you need to remove, I think. I must have forgotten to do this in the PMCC stuff I uploaded. 
> 
> ...
> 
> This is what Pyotr said you need to do to fix the insta kill when thrown

What's that code supposed to do?

**Comment by cimpyhigh** [comment]
@bb010g 
Tbh, I'm not sure. I don't have it in my build and it hasn't affected anything. Pyotr said he hasn't noticed anything yet, too. You can check for yourself, but to my knowledge all it does is fix Sami.

**Comment by PyotrLuzhin** [comment]
Okay, so I really should have taken out the Throw Release Points code a while ago. Honestly, I don't think it does anything, and it was added between 3.02 and 3.5, so I don't think it has any effect other than instantly killing unauthorized clones.

Remove this code:

C2771688 00000011
D8220018 807F0010
80630060 38820020
38A00000 3D408077
614A866C 7D4903A6
4E800421 C8220018
C05F0020 815F0010
812A0008 81290110
2C090000 41800044
2C09002F 4181003C
3D00901B 61087E00
1D290008 7C084C6E
EC000072 80EA0018
C0470040 EC0000B2
C042002C EC02002A
D0010014 C042003C
D041000C C0480004
60000000 00000000

**Comment by MlKe12** [comment]
Hello, I have tried to use the code with Project M CC but it don't work and i have the same problem as  CervantesE (loading brawl instead of PM). I'm using Dolphin and the current codes in /codes (this one : https://github.com/TheOriginalSINe/Project-M-CC/blob/master/codes/RSBE01.gct ) worked but not the code for adding Sami. Is it only a problem with Dolphin ?

**Comment by cimpyhigh** [comment]
@PyotrLuzhin 
Sorry if I stole your thunder...
@Mariokirby123 
Try this link: https://www.youtube.com/watch?v=ZoxVMnNe0WY Dowload is in description, video is by @PyotrLuzhin.

It's slightly out of date, but it works.

**Comment by MlKe12** [comment]
@cimpyhigh Thanks it's working now !

**Comment by ghost** [comment]
Approved

Instant death can be submitted as an issue and addressed in a new PR

**Comment by bb010g** [comment]
@PyotrLuzhin Rebase and we'll :shipit:.

**Comment by Darquezze** [comment]
https://docs.google.com/uc?id=0B_LEC2C41PtfblAxcXJ1RWZHUmc&export=download this build made by denz on discord should be added here

**Comment by bb010g** [comment]
@Darquezze PR it separately, and say what it does. This issue is for a PR for just adding Sami.

**Comment by Darquezze** [comment]
@bb010g this build includes Sami

**Comment by Darquezze** [comment]
Sami*

**Comment by bb010g** [comment]
Nothing got reverted by this, right?

**Comment by PyotrLuzhin** [comment]
Oh, by the way, for anyone who wants sami to have snake's sounds for now, CTRL+F for 04AD8A80 0000000F in your .gct or this codeset and replace the highlighted hex with 04AD8A80 00000025

**Pull request merged**
